apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-api
  labels:
    app: backend-api
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: backend-api
  template:
    metadata:
      labels:
        app: backend-api
    spec:
      containers:
        - name: backend-api
          image: 641240771475.dkr.ecr.us-east-1.amazonaws.com/starttech-backend-api:latest
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: REDIS_HOST
            - name: MONGO_URI
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: MONGO_URI
            - name: DB_NAME
              value: "muchtodo"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secrets
                  key: JWT_SECRET_KEY
            - name: ENABLE_CACHE
              value: "true"
          readinessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/health
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20